// E2E suite for the image analyzer tab (S18f), driven by @playwright/test.
//
// Binary TIFF fixtures are regenerated by the globalSetup in
// playwright.config.ts (which spawns tests/e2e/fixtures/generate-fixtures.mjs),
// so no binary is committed. Tests get a fresh browser context each, and the
// app defaults to English (i18n loadLang() returns "en" unless localStorage
// holds "de"), so assertions bind to the EN strings in apps/web/src/i18n.ts:
//
//   "Analyzer" / "Bildanalyse"   T.tabAnalyzer (chrome.ts renderHeader tabs)
//   "Pick file"                  T.imgPickFile (views/image.ts upload card)
//   "Run analysis"               T.imgRun (views/image.ts run button)
//   "D4sigma (ellipse)"          T.imgD4Sigma result tile label (tile helper)
//   "suppressed"                 T.imgSuppressed suppressed marker
//   "Export CSV" / "Export JSON" T.imgExportCsv / T.imgExportJson
//   "UPLOAD — IMAGE FILE"        T.imgUpload card title
//   "IMG · RAW RENDER"           chrome.ts header mode pill on the image tab
//   "Pick dark frame"            T.imgBgPickDark (views/image.ts dark picker)
//   "Dark frame dimensions 16×12 do not match image dimensions 64×48."  T.imgBgDarkDimMismatch
//
// The headline label is a plain div, so the ".result-tile" card class is used
// to disambiguate it from the identical row label in the diagnostics section
// once results have rendered.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test, type Download, type Locator, type Page } from "@playwright/test";

const FIXTURES_DIR = fileURLToPath(new URL("./fixtures/", import.meta.url));

async function openAnalyzerTab(page: Page): Promise<void> {
  await page.goto("/workbench.html");
  await page.getByRole("button", { name: "Analyzer", exact: true }).click();
  await expect(page.getByRole("button", { name: "Pick file", exact: true })).toBeVisible();
}

// The upload flow goes through a dynamically created <input type="file">
// (main.ts pickImageFile) that is clicked and never attached to the DOM, so
// the real file chooser is driven via the filechooser event. Decode runs in
// the image web worker; the run button becoming enabled is the UI signal
// that decoding finished.
async function uploadImage(page: Page, fixtureName: string): Promise<void> {
  const fileChooserPromise = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Pick file", exact: true }).click();
  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles(join(FIXTURES_DIR, fixtureName));
  await expect(page.getByText(fixtureName, { exact: true })).toBeVisible({ timeout: 15_000 });
  await expect(page.getByRole("button", { name: "Run analysis", exact: true })).toBeEnabled({ timeout: 15_000 });
}

function gray16Tiff(width: number, height: number): Buffer {
  const stripOffset = 8 + (2 + 9 * 12 + 4);
  const file = Buffer.alloc(stripOffset + width * height * 2);
  file.write("II", 0, "ascii");
  file.writeUInt16LE(42, 2);
  file.writeUInt32LE(8, 4);
  file.writeUInt16LE(9, 8);
  let offset = 10;
  const entry = (tag: number, type: number, value: number): void => {
    file.writeUInt16LE(tag, offset);
    file.writeUInt16LE(type, offset + 2);
    file.writeUInt32LE(1, offset + 4);
    if (type === 3) file.writeUInt16LE(value, offset + 8);
    else file.writeUInt32LE(value, offset + 8);
    offset += 12;
  };
  entry(256, 3, width);
  entry(257, 3, height);
  entry(258, 3, 16);
  entry(259, 3, 1);
  entry(262, 3, 1);
  entry(273, 4, stripOffset);
  entry(277, 3, 1);
  entry(278, 3, height);
  entry(279, 4, width * height * 2);
  file.writeUInt32LE(0, offset);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const dx = (x - (width - 1) / 2) / 6;
      const dy = (y - (height - 1) / 2) / 4;
      const value = 800 + 20_000 * Math.exp(-0.5 * (dx * dx + dy * dy));
      file.writeUInt16LE(Math.round(value), stripOffset + (y * width + x) * 2);
    }
  }
  return file;
}

async function uploadGeneratedImage(page: Page, name: string, buffer: Buffer): Promise<void> {
  const fileChooserPromise = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Pick file", exact: true }).click();
  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles({ name, mimeType: "image/tiff", buffer });
  await expect(page.getByText(name, { exact: true })).toBeVisible({ timeout: 15_000 });
  await expect(page.getByRole("button", { name: "Run analysis", exact: true })).toBeEnabled({ timeout: 15_000 });
}

async function beginCanvasTextCapture(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const capture = window as unknown as {
      modeForgeCanvasText?: string[];
      modeForgeCanvasTextPositions?: Array<{ text: string; x: number; y: number; canvasId: string }>;
      modeForgeOverlayPanels?: Array<{ x: number; y: number; width: number; height: number }>;
    };
    capture.modeForgeCanvasText = [];
    capture.modeForgeCanvasTextPositions = [];
    capture.modeForgeOverlayPanels = [];
    const fillText = CanvasRenderingContext2D.prototype.fillText;
    CanvasRenderingContext2D.prototype.fillText = function (text, ...args) {
      capture.modeForgeCanvasText?.push(String(text));
      capture.modeForgeCanvasTextPositions?.push({ text: String(text), x: Number(args[0]), y: Number(args[1]), canvasId: this.canvas.id });
      return fillText.call(this, text, ...args);
    };
    const fillRect = CanvasRenderingContext2D.prototype.fillRect;
    CanvasRenderingContext2D.prototype.fillRect = function (x, y, width, height) {
      if (this.canvas.id === "img-overlay" && this.fillStyle === "rgba(7, 10, 15, 0.72)") {
        capture.modeForgeOverlayPanels?.push({ x, y, width, height });
      }
      return fillRect.call(this, x, y, width, height);
    };
  });
}

async function canvasDrewText(page: Page, text: string): Promise<boolean> {
  return page.evaluate((expected) => {
    const capture = window as unknown as { modeForgeCanvasText?: string[] };
    return capture.modeForgeCanvasText?.includes(expected) ?? false;
  }, text);
}

async function canvasHasPurpleRectangleEdges(
  page: Page,
  imageWidth: number,
  imageHeight: number,
  rects: ReadonlyArray<{ x0: number; y0: number; width: number; height: number }>,
): Promise<boolean> {
  return page.locator("#img-overlay").evaluate((element, expected) => {
    const canvas = element as HTMLCanvasElement;
    const ctx = canvas.getContext("2d");
    if (!ctx) return false;
    const image = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const capture = window as unknown as {
      modeForgeCanvasTextPositions?: Array<{ text: string; x: number; y: number; canvasId: string }>;
      modeForgeOverlayPanels?: Array<{ x: number; y: number; width: number; height: number }>;
    };
    const legendText = (capture.modeForgeCanvasTextPositions ?? [])
      .filter((entry) => entry.canvasId === "img-overlay" && entry.text === "background rectangle")
      .pop();
    if (!legendText) return false;
    const legendBoxes = (capture.modeForgeOverlayPanels ?? []).filter(
      (panel) =>
        legendText.x >= panel.x &&
        legendText.x <= panel.x + panel.width &&
        legendText.y >= panel.y &&
        legendText.y <= panel.y + panel.height,
    );
    const legendBox = legendBoxes[legendBoxes.length - 1];
    if (!legendBox) return false;
    const purple = (x: number, y: number): boolean => {
      if (x < 0 || y < 0 || x >= canvas.width || y >= canvas.height) return false;
      const offset = (y * canvas.width + x) * 4;
      return image.data[offset + 3] === 255 && image.data[offset] === 197 && image.data[offset + 1] === 139 && image.data[offset + 2] === 242;
    };
    const inLegend = (x: number, y: number): boolean =>
      x >= legendBox.x - 2 && x <= legendBox.x + legendBox.width + 2 && y >= legendBox.y - 2 && y <= legendBox.y + legendBox.height + 2;
    const scaleX = canvas.width / expected.imageWidth;
    const scaleY = canvas.height / expected.imageHeight;
    const band = Math.max(2, Math.ceil(Math.max(scaleX, scaleY) * 1.5));
    const hitBand = (x0: number, x1: number, y0: number, y1: number): boolean => {
      for (let y = Math.floor(y0); y <= Math.ceil(y1); y += 1) {
        for (let x = Math.floor(x0); x <= Math.ceil(x1); x += 1) {
          if (!inLegend(x, y) && purple(x, y)) return true;
        }
      }
      return false;
    };
    return expected.rects.every((rect) => {
      const x0 = (rect.x0 + 0.5) * scaleX;
      const x1 = (rect.x0 + rect.width - 0.5) * scaleX;
      const y0 = (rect.y0 + 0.5) * scaleY;
      const y1 = (rect.y0 + rect.height - 0.5) * scaleY;
      return (
        hitBand(x0, x1, y0 - band, y0 + band) &&
        hitBand(x0, x1, y1 - band, y1 + band) &&
        hitBand(x0 - band, x0 + band, y0, y1) &&
        hitBand(x1 - band, x1 + band, y0, y1)
      );
    });
  }, { imageWidth, imageHeight, rects });
}

async function dragFullFrameImage(page: Page, from: { x: number; y: number }, to: { x: number; y: number }, width: number, height: number): Promise<void> {
  const box = await page.locator("#img-canvas").boundingBox();
  if (!box) throw new Error("image canvas is not laid out");
  const point = (value: { x: number; y: number }) => ({
    x: box.x + (value.x / width) * box.width,
    y: box.y + (value.y / height) * box.height,
  });
  const start = point(from);
  const end = point(to);
  await page.mouse.move(start.x, start.y);
  await page.mouse.down();
  await page.mouse.move(end.x, end.y);
  await page.mouse.up();
}

async function bgRectFields(page: Page, index: number): Promise<{ x0: number; y0: number; width: number; height: number }> {
  const values = await Promise.all(
    ["bgRectX0", "bgRectY0", "bgRectW", "bgRectH"].map((key) => page.locator(`input[data-k="${key}-${index}"]`).inputValue()),
  );
  return { x0: Number(values[0]), y0: Number(values[1]), width: Number(values[2]), height: Number(values[3]) };
}

async function roiFields(page: Page): Promise<string[]> {
  return Promise.all(["imgRoiX0", "imgRoiY0", "imgRoiW", "imgRoiH"].map((key) => page.locator(`input[data-k="${key}"]`).inputValue()));
}

// Dark-frame picker uses the same detached <input type="file"> pattern
// (main.ts pickDarkFrameFile) and is only in the DOM after bgMethod is
// dark-frame. The filechooser event is the upload signal; callers wait for
// the loaded note or a typed dark-error string after setFiles.
async function uploadDarkFrame(page: Page, fixtureName: string): Promise<void> {
  const fileChooserPromise = page.waitForEvent("filechooser");
  await page.locator('button[data-act="img-bg-pick-dark"]').click();
  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles(join(FIXTURES_DIR, fixtureName));
}

async function runAnalysis(page: Page): Promise<Locator> {
  await page.getByRole("button", { name: "Run analysis", exact: true }).click();
  // Result headline tile labelled "D4sigma (ellipse)" (T.imgD4Sigma).
  return page.locator(".result-tile").filter({ hasText: "D4sigma (ellipse)" }).locator(".tile-value");
}

async function downloadText(download: Download): Promise<string> {
  const filePath = await download.path();
  if (typeof filePath !== "string") throw new Error("download did not produce a local file");
  return readFileSync(filePath, "utf8");
}

type AnalysisJson = {
  symmetry: { axialAsymmetryX: number | null; axialAsymmetryY: number | null } | null;
};

async function downloadAnalysisJson(page: Page): Promise<AnalysisJson> {
  const downloadPromise = page.waitForEvent("download");
  await page.locator('button[data-act="img-export-json"]').click();
  return JSON.parse(await downloadText(await downloadPromise)) as AnalysisJson;
}

test("the analyzer tab is reachable from the header", async ({ page }) => {
  await page.goto("/workbench.html");
  const tab = page.getByRole("button", { name: "Analyzer", exact: true });
  await expect(tab).toBeVisible();
  await tab.click();
  await expect(page.getByText("UPLOAD — IMAGE FILE", { exact: true })).toBeVisible();
  await expect(page.getByText("IMG · RAW RENDER", { exact: true })).toBeVisible();
});

test("gauss_released.tif renders a released D4sigma headline", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  const headline = await runAnalysis(page);
  // decode + analyze run in the image web worker, so wait generously.
  await expect(headline).toHaveText(/^\d/, { timeout: 30_000 });
  await expect(headline).toContainText("px");
  await expect(headline).not.toContainText("suppressed");
});

test("residual diagnostics show a numeric signed colorbar, relabel modes, and preserve manual-scale drafts", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  const headline = await runAnalysis(page);
  await expect(headline).toContainText("px", { timeout: 30_000 });

  const ticks = page.locator("#img-residual-colorbar-ticks .img-colorbar-tick");
  await expect(ticks).toHaveCount(3);
  const countsTicks = await ticks.allTextContents();
  expect(countsTicks.some((text) => /counts$/.test(text))).toBe(true);
  expect(countsTicks.some((text) => /^-/.test(text))).toBe(true);

  await page.locator('button[data-act="img-residual-mode"][data-arg="percent-peak"]').click();
  await expect(page.locator('button[data-act="img-residual-mode"][data-arg="percent-peak"]')).toHaveClass(/active/);
  await expect(ticks.first()).toContainText("%");
  expect(await ticks.allTextContents()).not.toEqual(countsTicks);

  await page.locator('button[data-act="img-residual-mode"][data-arg="counts"]').click();
  const manualScale = page.locator('input[data-k="imgResidualManualScale"]');
  await manualScale.fill("");
  await manualScale.pressSequentially("0.");
  await expect(manualScale).toHaveValue("0.");
  await manualScale.fill("");
  await manualScale.pressSequentially("1e");
  await expect(manualScale).toHaveValue("1e");
  await manualScale.fill("2");
  await expect(manualScale).toHaveValue("2");
  await expect(ticks.first()).toHaveText("2 counts");
  await expect(ticks.last()).toHaveText("-2 counts");
});

test("flat_zero_noise.tif disables sigma_B residual normalization with its reason", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "flat_zero_noise.tif");
  const headline = await runAnalysis(page);
  await expect(headline).toContainText("px", { timeout: 30_000 });
  const sigmaMode = page.locator('button[data-act="img-residual-mode"][data-arg="sigma"]');
  await expect(sigmaMode).toBeDisabled();
  await expect(sigmaMode).toHaveAttribute("title", /sigma_B normalization requires sigma_B > 0/);
});

test("two_lobe_suppressed.tif renders the suppressed headline", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "two_lobe_suppressed.tif");
  const headline = await runAnalysis(page);
  await expect(headline).toContainText("suppressed", { timeout: 30_000 });
  // The suppressed marker must be followed by an actual suppression reason.
  await expect(headline).toHaveText(/^suppressed:\s*\S/);
});

test("CSV and JSON exports download non-empty analysis content", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  const headline = await runAnalysis(page);
  await expect(headline).toContainText("px", { timeout: 30_000 });

  // data-act selectors: the header carries a project-level "Export JSON"
  // button, so the accessible name alone is ambiguous (strict-mode clash).
  const exportCsv = page.locator('button[data-act="img-export-csv"]');
  const exportJson = page.locator('button[data-act="img-export-json"]');
  await expect(exportCsv).toBeVisible();
  await expect(exportJson).toBeVisible();

  const csvDownloadPromise = page.waitForEvent("download");
  await exportCsv.click();
  const csvDownload = await csvDownloadPromise;
  expect(csvDownload.suggestedFilename()).toBe("gauss_released.analysis.csv");
  const csvText = await downloadText(csvDownload);
  expect(csvText).toContain("key,value");
  expect(csvText).toContain("released_d4sigma");

  const jsonDownloadPromise = page.waitForEvent("download");
  await exportJson.click();
  const jsonDownload = await jsonDownloadPromise;
  expect(jsonDownload.suggestedFilename()).toBe("gauss_released.analysis.json");
  const jsonText = await downloadText(jsonDownload);
  expect(JSON.parse(jsonText).releasedD4sigma).toHaveProperty("d4SigmaMajorPx");
});

test("the language toggle switches the analyzer tab label", async ({ page }) => {
  await page.goto("/workbench.html");
  await expect(page.getByRole("button", { name: "Analyzer", exact: true })).toBeVisible();

  await page.getByRole("button", { name: "DE", exact: true }).click();
  await expect(page.getByRole("button", { name: "Bildanalyse", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Analyzer", exact: true })).toHaveCount(0);

  await page.getByRole("button", { name: "EN", exact: true }).click();
  await expect(page.getByRole("button", { name: "Analyzer", exact: true })).toBeVisible();
});

test("robust-plane background on a ramp recovers the released D4sigma headline", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "ramp_background.tif");
  // Background controls (S18e-C part B): robust plane over the four corner
  // rectangles the part-A corners action fills.
  await page.locator('select[data-k="imgBgMethod"]').selectOption("robust-plane");
  await page.locator('button[data-act="img-bg-rect-corners"]').click();
  const headline = await runAnalysis(page);
  await expect(headline).toHaveText(/^\d/, { timeout: 30_000 });
  await expect(headline).toContainText("px");
  await expect(headline).not.toContainText("suppressed");
});

test("Auto mode runs both automatic engine modes, shows provenance, and restores the defaults", async ({ page }) => {
  const width = 64;
  const height = 48;
  const cornerRects = [
    { x0: 0, y0: 0, width: 8, height: 6 },
    { x0: 56, y0: 0, width: 8, height: 6 },
    { x0: 0, y0: 42, width: 8, height: 6 },
    { x0: 56, y0: 42, width: 8, height: 6 },
  ];
  await beginCanvasTextCapture(page);
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");

  await page.locator('button[data-act="img-auto-mode"]').click();
  await expect(page.locator('select[data-k="imgBgMethod"]')).toHaveValue("auto");
  await expect(page.locator('button[data-act="img-roi-mode"][data-arg="auto"]')).toHaveClass(/active/);
  await expect(page.locator('button[data-act="img-auto-mode"]')).toHaveClass(/active/);

  const headline = await runAnalysis(page);
  await expect(headline).toHaveText(/^\d/, { timeout: 30_000 });
  await expect(headline).toContainText("px");
  await expect(page.getByText("Auto background: robust plane over corner references.", { exact: true })).toBeVisible({ timeout: 30_000 });

  // This compact fixture already renders at full frame: the close-up selector
  // is intentionally absent when no tighter view can be derived.
  await expect
    .poll(() => canvasHasPurpleRectangleEdges(page, width, height, cornerRects), {
      message: "automatic corner references use the established purple background-rectangle overlay path",
    })
    .toBe(true);

  await page.locator('button[data-act="img-auto-mode"]').click();
  await expect(page.locator('select[data-k="imgBgMethod"]')).toHaveValue("none");
  await expect(page.locator('button[data-act="img-roi-mode"][data-arg="full"]')).toHaveClass(/active/);
  await expect(page.locator('button[data-act="img-auto-mode"]')).not.toHaveClass(/active/);
});

test("background rectangles render, edit independently from the ROI, and reset to ROI mode with method none", async ({ page }) => {
  const width = 160;
  const height = 128;
  await beginCanvasTextCapture(page);
  await openAnalyzerTab(page);
  await uploadGeneratedImage(page, "bg_draw_mode.tif", gray16Tiff(width, height));
  await page.locator('select[data-k="imgBgMethod"]').selectOption("rect-median");
  await page.locator('button[data-act="img-bg-rect-add"]').click();
  const headline = await runAnalysis(page);
  await expect(headline).toContainText("px", { timeout: 30_000 });
  await expect(page.locator('button[data-act="img-roi-mode"][data-arg="full"]')).toHaveClass(/active/);

  const imageCanvas = page.locator("#img-canvas");
  const bgDrawButton = page.getByRole("button", { name: "Background rectangle", exact: true });
  await expect(bgDrawButton).toBeVisible();
  await page.evaluate(() => {
    const capture = window as unknown as {
      modeForgeCanvasText?: string[];
      modeForgeCanvasTextPositions?: Array<{ text: string; x: number; y: number; canvasId: string }>;
      modeForgeOverlayPanels?: Array<{ x: number; y: number; width: number; height: number }>;
    };
    capture.modeForgeCanvasText = [];
    capture.modeForgeCanvasTextPositions = [];
    capture.modeForgeOverlayPanels = [];
  });
  await bgDrawButton.click();
  await expect
    .poll(() => imageCanvas.evaluate((element) => (element as HTMLCanvasElement).width), { message: "background draw mode forces the full frame" })
    .toBe(width);
  await expect
    .poll(() => imageCanvas.evaluate((element) => (element as HTMLCanvasElement).height), { message: "background draw mode keeps the full frame height" })
    .toBe(height);
  await expect(page.locator('button[data-act="img-roi-mode"][data-arg="full"]')).toHaveClass(/active/);
  await expect(page.locator('button[data-act="img-preview-view"][data-arg="closeup"]')).toBeDisabled();
  await expect(page.locator('button[data-act="img-preview-view"][data-arg="full"]')).toHaveAttribute(
    "title",
    "Full-frame view is required while drawing background rectangles.",
  );
  const initialRect = await bgRectFields(page, 0);
  await expect
    .poll(() => canvasHasPurpleRectangleEdges(page, width, height, [initialRect]), {
      message: "the default full-frame ROI and legend leave every background-rectangle edge pure purple",
    })
    .toBe(true);
  await expect.poll(() => canvasDrewText(page, "background rectangle"), { message: "background-rectangle legend entry is painted" }).toBe(true);

  // The remaining interaction coverage starts from the four standard corner
  // samples; the stricter oracle above deliberately used one occupied corner.
  await page.locator('button[data-act="img-bg-rect-corners"]').click();
  await page.locator('button[data-act="img-roi-mode"][data-arg="rect"]').click();
  const roiBefore = await roiFields(page);
  await dragFullFrameImage(page, { x: 55, y: 40 }, { x: 75, y: 55 }, width, height);
  await expect(page.locator('input[data-k="bgRectX0-4"]')).toBeVisible();
  expect(await roiFields(page)).toEqual(roiBefore);

  // Select and move the newly created rectangle, then exercise an edge and a
  // corner resize. Each commit stays on the background-rectangle list.
  const created = await bgRectFields(page, 4);
  await dragFullFrameImage(
    page,
    { x: created.x0 + created.width / 2, y: created.y0 + created.height / 2 },
    { x: created.x0 + created.width / 2 + 10, y: created.y0 + created.height / 2 + 5 },
    width,
    height,
  );
  const moved = await bgRectFields(page, 4);
  expect(moved.x0).not.toBe(created.x0);
  expect(moved.y0).not.toBe(created.y0);
  await dragFullFrameImage(page, { x: moved.x0 + moved.width, y: moved.y0 + moved.height / 2 }, { x: moved.x0 + moved.width + 10, y: moved.y0 + moved.height / 2 }, width, height);
  const edgeResized = await bgRectFields(page, 4);
  expect(edgeResized.width).toBeGreaterThan(moved.width);
  await dragFullFrameImage(
    page,
    { x: edgeResized.x0 + edgeResized.width, y: edgeResized.y0 + edgeResized.height },
    { x: edgeResized.x0 + edgeResized.width + 10, y: edgeResized.y0 + edgeResized.height + 10 },
    width,
    height,
  );
  const cornerResized = await bgRectFields(page, 4);
  expect(cornerResized.width).toBeGreaterThan(edgeResized.width);
  expect(cornerResized.height).toBeGreaterThan(edgeResized.height);

  // A new rectangle started in empty space and ending over the fifth sample
  // overlaps it. Moving their shared interior must select the later (topmost)
  // rectangle, not the earlier one.
  await dragFullFrameImage(
    page,
    { x: cornerResized.x0 - 10, y: cornerResized.y0 - 10 },
    { x: cornerResized.x0 + 10, y: cornerResized.y0 + 10 },
    width,
    height,
  );
  const fifthBeforeOverlapMove = await bgRectFields(page, 4);
  const sixthBeforeOverlapMove = await bgRectFields(page, 5);
  await dragFullFrameImage(
    page,
    { x: Math.max(fifthBeforeOverlapMove.x0, sixthBeforeOverlapMove.x0) + 5, y: Math.max(fifthBeforeOverlapMove.y0, sixthBeforeOverlapMove.y0) + 5 },
    { x: Math.max(fifthBeforeOverlapMove.x0, sixthBeforeOverlapMove.x0) + 15, y: Math.max(fifthBeforeOverlapMove.y0, sixthBeforeOverlapMove.y0) + 10 },
    width,
    height,
  );
  expect(await bgRectFields(page, 4)).toEqual(fifthBeforeOverlapMove);
  expect(await bgRectFields(page, 5)).not.toEqual(sixthBeforeOverlapMove);
  await page.locator('button[data-act="img-bg-rect-remove"][data-i="5"]').click();
  await expect(page.locator('input[data-k="bgRectX0-5"]')).toHaveCount(0);

  // ROI drag is independent: it writes only the ROI fields. Switching the
  // method to none removes the target control and keeps ROI drag as the
  // forced fallback target (R-22).
  const bgBeforeRoi = await bgRectFields(page, 4);
  await page.getByRole("button", { name: "Measurement ROI", exact: true }).click();
  await dragFullFrameImage(page, { x: 25, y: 30 }, { x: 45, y: 45 }, width, height);
  expect(await roiFields(page)).not.toEqual(roiBefore);
  expect(await bgRectFields(page, 4)).toEqual(bgBeforeRoi);

  await page.locator('select[data-k="imgBgMethod"]').selectOption("none");
  await expect(page.getByRole("button", { name: "Background rectangle", exact: true })).toHaveCount(0);
  const roiAfterMethodReset = await roiFields(page);
  await dragFullFrameImage(page, { x: 35, y: 37 }, { x: 45, y: 42 }, width, height);
  expect(await roiFields(page)).not.toEqual(roiAfterMethodReset);

  // The method-none fallback has no background-rectangle editor. Reopen the
  // rectangle-backed editor to verify that the fallback drag left its saved
  // rectangle untouched.
  await page.locator('select[data-k="imgBgMethod"]').selectOption("rect-median");
  await expect(page.locator('input[data-k="bgRectX0-4"]')).toBeVisible();
  expect(await bgRectFields(page, 4)).toEqual(bgBeforeRoi);

  const pngDownloadPromise = page.waitForEvent("download");
  await page.locator('button[data-act="img-export-png"]').click();
  const pngDownload = await pngDownloadPromise;
  expect(pngDownload.suggestedFilename()).toBe("bg_draw_mode.closeup.png");
  const pngPath = await pngDownload.path();
  if (typeof pngPath !== "string") throw new Error("PNG export did not produce a local file");
  expect(readFileSync(pngPath).subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
});

test("a matching dark pedestal changes exported axial symmetry from the none-method run", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  await page.locator('select[data-k="imgBgMethod"]').selectOption("none");
  const noneHeadline = await runAnalysis(page);
  await expect(noneHeadline).toContainText("px", { timeout: 30_000 });
  const noneReport = await downloadAnalysisJson(page);
  if (noneReport.symmetry === null) throw new Error("none-method analysis did not export symmetry");

  await page.locator('select[data-k="imgBgMethod"]').selectOption("dark-frame");
  await expect(page.locator('button[data-act="img-bg-pick-dark"]')).toBeVisible();
  await uploadDarkFrame(page, "dark_pedestal.tif");
  // Decode is async; the loaded note (T.imgBgDarkLoaded) is the UI signal.
  await expect(page.getByText("dark_pedestal.tif", { exact: false })).toBeVisible({ timeout: 15_000 });
  await expect(page.getByText("Dark frame dimensions 16×12 do not match image dimensions 64×48.", { exact: true })).toHaveCount(0);
  await expect(page.getByText("The dark frame file could not be read.", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Run analysis", exact: true })).toBeEnabled();
  const darkHeadline = await runAnalysis(page);
  await expect(darkHeadline).toContainText("px", { timeout: 30_000 });
  const darkReport = await downloadAnalysisJson(page);
  if (darkReport.symmetry === null) throw new Error("dark-frame analysis did not export symmetry");

  expect(darkReport.symmetry.axialAsymmetryX).not.toBe(noneReport.symmetry.axialAsymmetryX);
  expect(darkReport.symmetry.axialAsymmetryY).not.toBe(noneReport.symmetry.axialAsymmetryY);
});

test("dark_small.tif shows the dark-frame dimensions mismatch error", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  await page.locator('select[data-k="imgBgMethod"]').selectOption("dark-frame");
  await expect(page.locator('button[data-act="img-bg-pick-dark"]')).toBeVisible();
  await uploadDarkFrame(page, "dark_small.tif");
  await expect(page.getByText("Dark frame dimensions 16×12 do not match image dimensions 64×48.", { exact: true })).toBeVisible({
    timeout: 15_000,
  });
});

test("suggested ROI applies back into the rectangle inputs", async ({ page }) => {
  await openAnalyzerTab(page);
  await uploadImage(page, "gauss_released.tif");
  await runAnalysis(page);
  // The informational suggestion line (T.imgSuggestedRoi) is rendered from
  // the result's roi.suggestion.
  await expect(page.getByText("Suggested ROI", { exact: false })).toBeVisible({ timeout: 30_000 });
  await page.locator('button[data-act="img-apply-suggestion"]').click();
  // Applying the suggestion switches ROI mode to rectangle and fills the
  // four numeric inputs (data-k names from views/image.ts).
  for (const key of ["imgRoiX0", "imgRoiY0", "imgRoiW", "imgRoiH"]) {
    await expect(page.locator(`input[data-k="${key}"]`)).toHaveValue(/\d/);
  }
});
